### ISSUE TITLE
Possibility of adding a new field type

### ISSUE THREAD

**Issue by qomhmd** [vanderbilt-redcap/external-module-framework-docs#6]
Hello,
**Multiple files** upload field (with additional perks of **saving into server** as files not encoded in the database) seemingly is not a built-in feature in REDCap. To have it, is there a way to add a custom field to the form UI and receive all files in the backend with the submission of the data entry form?

**Comment by mmcev106** [comment]
I don't think this is the appropriate place to ask that question.  You may want to post it here:
https://redcap.vanderbilt.edu/community/
